apiVersion: v1
kind: ConfigMap
metadata:
  name: spark-config
  namespace: default
data:
  spark-defaults.conf: |
    spark.master=k8s://https://34.27.223.243
    spark.ui.port=4040
    spark.driver.host=spark-driver-example
    spark.driver.bindAddress=0.0.0.0
    spark.driver.port=29413
    spark.kubernetes.pyspark.pythonVersion=3
    spark.pyspark.python=/usr/bin/python3
    spark.pyspark.driver.python=/usr/bin/python3
    spark.kubernetes.container.image=apache/spark:3.3.3-python3
    spark.kubernetes.namespace=default
    spark.kubernetes.executor.request.cores=1.0
    spark.executor.instances=1
#    spark.jars=gs://hadoop-lib/gcs/gcs-connector-latest-hadoop3.jar
#    spark.hadoop.fs.gs.impl=com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystem
